### ISSUE TITLE
Валидация

### ISSUE THREAD

**Issue by pavluk** [JoomlaZen/plg_system_personaldata#1]
Добавьте собственную валидацию что бы можно было вставлять поле в любую форму.

**Comment by Septdir** [comment]
Как раз, над этим работаю. Уже почти закончил.

**Comment by Septdir** [comment]
Включено в новую  версию [https://github.com/JoomlaZen/plg_system_personaldata/releases/tag/0.7.1](https://github.com/JoomlaZen/plg_system_personaldata/releases/tag/0.7.1l)
